#
# TABLE STRUCTURE FOR: activity_logs
#

DROP TABLE IF EXISTS `activity_logs`;

CREATE TABLE `activity_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `module` varchar(50) NOT NULL,
  `sub_module` varchar(50) DEFAULT NULL,
  `item_id` varchar(50) DEFAULT NULL,
  `item_name` varchar(255) DEFAULT NULL,
  `action` varchar(50) NOT NULL,
  `data_before` longtext,
  `data_after` longtext,
  `user_id` int(11) DEFAULT NULL,
  `user_name` varchar(100) DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` text,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_module` (`module`),
  KEY `idx_action` (`action`),
  KEY `idx_user` (`user_id`),
  KEY `idx_created` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=92 DEFAULT CHARSET=utf8mb4;

INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (1, 'AUTH', NULL, '1', 'Super Administrator', 'LOGIN', NULL, NULL, 1, 'Super Administrator', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-04 23:11:29');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (2, 'AUTH', NULL, '1', 'Super Administrator', 'LOGOUT', NULL, NULL, 1, 'Super Administrator', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-04 23:13:37');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (3, 'AUTH', NULL, '1', 'Super Administrator', 'LOGIN', NULL, NULL, 1, 'Super Administrator', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-04 23:14:13');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (4, 'AUTH', NULL, '1', 'Super Administrator', 'LOGIN', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:16:34');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (5, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"sidebar\",\"skin_color\":\"blue\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"adminlte3\",\"sidebar_layout\":\"sidebar\",\"skin_color\":\"blue\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:16:47');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (6, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte3\",\"sidebar_layout\":\"sidebar\",\"skin_color\":\"blue\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"adminlte3\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"blue\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:16:55');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (7, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte3\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"blue\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"blue\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:17:04');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (8, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"blue\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"adminlte3\",\"sidebar_layout\":\"sidebar\",\"skin_color\":\"blue\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:17:16');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (9, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte3\",\"sidebar_layout\":\"sidebar\",\"skin_color\":\"blue\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"sidebar\",\"skin_color\":\"blue\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:17:23');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (10, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"sidebar\",\"skin_color\":\"blue\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"blue\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-04 23:19:47');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (11, 'AUTH', NULL, '1', 'Super Administrator', 'LOGOUT', NULL, NULL, 1, 'Super Administrator', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-04 23:21:46');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (12, 'AUTH', NULL, NULL, NULL, 'LOGOUT', NULL, NULL, NULL, NULL, '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-04 23:24:03');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (13, 'AUTH', NULL, '1', 'Super Administrator', 'LOGOUT', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:25:14');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (14, 'AUTH', NULL, '1', 'Super Administrator', 'LOGIN', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:29:44');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (15, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"blue\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"black\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:30:31');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (16, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"black\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"red\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:30:48');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (17, 'AUTH', NULL, '1', 'Super Administrator', 'LOGOUT', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:31:26');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (18, 'AUTH', NULL, '1', 'Super Administrator', 'LOGIN', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:31:33');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (19, 'AUTH', NULL, '1', 'Super Administrator', 'LOGIN', NULL, NULL, 1, 'Super Administrator', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-04 23:37:19');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (20, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"tabler\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"red\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"adminlte3\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"red\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:40:10');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (21, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte3\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"red\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"red\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:40:26');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (22, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"red\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"sidebar\",\"skin_color\":\"red\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:40:33');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (23, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"sidebar\",\"skin_color\":\"red\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"tabler\",\"sidebar_layout\":\"sidebar\",\"skin_color\":\"red\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:40:40');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (24, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"tabler\",\"sidebar_layout\":\"sidebar\",\"skin_color\":\"red\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"red\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:40:54');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (25, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"red\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"adminlte3\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"red\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:41:00');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (26, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte3\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"red\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"adminlte3\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"blue\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:41:19');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (27, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte3\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"blue\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"blue\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:42:10');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (28, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"blue\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"tabler\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"blue\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:44:59');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (29, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"tabler\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"blue\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"blue\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:45:27');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (30, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"blue\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"active_theme\":\"adminlte3\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"blue\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:45:34');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (31, 'AUTH', NULL, '1', 'Super Administrator', 'LOGOUT', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:49:34');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (32, 'AUTH', NULL, '1', 'Super Administrator', 'LOGIN', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:50:29');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (33, 'SYSTEM', 'MENU', '13', 'My Profile', 'DELETE', '{\"id\":\"13\",\"menu_name\":\"My Profile\",\"menu_icon\":\"fa fa-user\",\"menu_link\":\"admin\\/profile\",\"parent_id\":null,\"menu_order\":\"99\",\"menu_status\":\"1\",\"created_at\":\"2026-03-04 23:44:51\",\"updated_at\":null}', NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:50:49');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (34, 'SYSTEM', 'MENU', '12', 'My Profile', 'DELETE', '{\"id\":\"12\",\"menu_name\":\"My Profile\",\"menu_icon\":\"fa fa-user\",\"menu_link\":\"admin\\/profile\",\"parent_id\":null,\"menu_order\":\"99\",\"menu_status\":\"1\",\"created_at\":\"2026-03-04 23:44:17\",\"updated_at\":null}', NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:50:54');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (35, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"blue\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"green\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:51:43');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (36, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"green\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"red\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:51:48');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (37, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"red\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:51:53');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (38, 'SYSTEM', 'USERS', '1', 'Super Administrator', 'BLOCK', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:54:01');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (39, 'SYSTEM', 'USERS', '1', 'Super Administrator', 'UNBLOCK', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-04 23:54:03');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (40, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"CI3 Enterprise Starter Kit\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"REKONLINK\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"login_attempts\":\"3\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 00:08:57');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (41, 'SYSTEM', 'USERS', '1', 'Super Administrator', 'BLOCK', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 00:09:46');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (42, 'SYSTEM', 'USERS', '1', 'Super Administrator', 'UNBLOCK', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 00:09:49');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (43, 'SYSTEM', 'BACKUP', NULL, 'backup_2026-03-05_00-11-23.sql', 'BACKUP_CREATE', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 00:11:23');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (44, 'SYSTEM', 'USERS', '2', 'tes sof delete', 'CREATE', NULL, '{\"username\":\"tes sof delete\",\"nama\":\"tes sof delete\",\"email\":\"tessofdelete@gmail.com\",\"no_telp\":\"tes sof delete\",\"role_id\":\"2\",\"is_active\":1,\"created_at\":\"2026-03-05 00:28:58\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 00:28:58');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (45, 'SYSTEM', 'USERS', '2', 'tes sof delete', 'DELETE', '{\"id\":\"2\",\"username\":\"tes sof delete\",\"password\":\"9457f5f5626cff8c0afa2ae47314273a\",\"nama\":\"tes sof delete\",\"email\":\"tessofdelete@gmail.com\",\"no_telp\":\"tes sof delete\",\"avatar\":\"default.png\",\"role_id\":\"2\",\"is_active\":\"1\",\"is_blocked\":\"0\",\"failed_login\":\"0\",\"last_login\":null,\"created_at\":\"2026-03-05 00:28:58\",\"updated_at\":null,\"deleted_at\":null,\"role_name\":\"Admin\"}', NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 00:29:06');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (46, 'SYSTEM', 'USERS', '2', 'tes sof delete', 'RESTORE', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 00:38:51');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (47, 'SYSTEM', 'USERS', '2', 'tes sof delete', 'DELETE', '{\"id\":\"2\",\"username\":\"tes sof delete\",\"password\":\"9457f5f5626cff8c0afa2ae47314273a\",\"nama\":\"tes sof delete\",\"email\":\"tessofdelete@gmail.com\",\"no_telp\":\"tes sof delete\",\"avatar\":\"default.png\",\"role_id\":\"2\",\"is_active\":\"1\",\"is_blocked\":\"0\",\"failed_login\":\"0\",\"last_login\":null,\"created_at\":\"2026-03-05 00:28:58\",\"updated_at\":null,\"deleted_at\":null,\"role_name\":\"Admin\"}', NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 00:39:06');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (48, 'SYSTEM', 'ROLES', '3', 'User', 'DELETE', '{\"id\":\"3\",\"role_name\":\"User\",\"description\":\"Akses user biasa\",\"is_superadmin\":\"0\",\"created_at\":\"2026-03-04 23:10:23\",\"updated_at\":null,\"deleted_at\":null}', NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 00:43:37');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (49, 'SYSTEM', 'ROLES', '3', 'User', 'RESTORE', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 00:43:48');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (50, 'SYSTEM', 'USERS', '1', 'Super Administrator', 'UPDATE', '{\"id\":\"1\",\"username\":\"admin\",\"password\":\"0192023a7bbd73250516f069df18b500\",\"nama\":\"Super Administrator\",\"email\":\"admin@starterkit.local\",\"no_telp\":null,\"avatar\":\"default.png\",\"role_id\":\"1\",\"is_active\":\"1\",\"is_blocked\":\"0\",\"failed_login\":\"0\",\"last_login\":\"2026-03-04 23:50:29\",\"created_at\":\"2026-03-04 23:10:23\",\"updated_at\":\"2026-03-05 00:09:49\",\"deleted_at\":null,\"role_name\":\"Super Admin\"}', '{\"nama\":\"Super Administrator\",\"email\":\"admin@starterkit.local\",\"no_telp\":\"081254593695\",\"role_id\":\"1\",\"is_active\":\"1\",\"updated_at\":\"2026-03-05 00:54:17\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 00:54:17');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (51, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"REKONLINK\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kit\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\"}', '{\"app_name\":\"REKONLINK\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kits\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\",\"maintenance_mode\":\"0\",\"maintenance_message\":\"\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 01:20:19');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (52, 'SYSTEM', 'USERS', '1', 'Super Administrator', 'UPDATE', '{\"id\":\"1\",\"username\":\"admin\",\"password\":\"0192023a7bbd73250516f069df18b500\",\"nama\":\"Super Administrator\",\"email\":\"admin@starterkit.local\",\"no_telp\":\"081254593695\",\"avatar\":\"default.png\",\"role_id\":\"1\",\"is_active\":\"1\",\"is_blocked\":\"0\",\"failed_login\":\"0\",\"last_login\":\"2026-03-04 23:50:29\",\"created_at\":\"2026-03-04 23:10:23\",\"updated_at\":\"2026-03-05 00:54:17\",\"deleted_at\":null,\"role_name\":\"Super Admin\"}', '{\"nama\":\"Super Administrator\",\"username\":\"admin\",\"updated_at\":\"2026-03-05 01:21:38\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 01:21:38');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (53, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"REKONLINK\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kits\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\",\"maintenance_mode\":\"0\",\"maintenance_message\":\"\"}', '{\"app_name\":\"REKONLINK\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kits\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\",\"maintenance_mode\":\"1\",\"maintenance_message\":\"Maaf lagi gangguan yah\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 01:25:17');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (54, 'AUTH', NULL, '1', 'Super Administrator', 'LOGOUT', NULL, NULL, 1, 'Super Administrator', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-05 01:25:34');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (55, 'SYSTEM', 'USERS', '3', 'Budi Darma', 'CREATE', NULL, '{\"username\":\"darma9989\",\"nama\":\"Budi Darma\",\"email\":\"darma09091989@gmail.com\",\"no_telp\":\"081254593695\",\"role_id\":\"2\",\"is_active\":1,\"created_at\":\"2026-03-05 01:26:58\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 01:26:58');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (56, 'AUTH', NULL, '3', 'Budi Darma', 'LOGIN_FAILED', NULL, '{\"reason\":\"Wrong password\",\"attempt\":1}', NULL, NULL, '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-05 01:27:09');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (57, 'SYSTEM', 'USERS', '3', 'Budi Darma', 'PASSWORD_RESET', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 01:27:22');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (58, 'AUTH', NULL, '3', 'Budi Darma', 'LOGIN', NULL, NULL, 3, 'Budi Darma', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-05 01:27:28');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (59, 'SYSTEM', 'BACKUP', NULL, 'backup_2026-03-05_01-28-31.sql', 'BACKUP_CREATE', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 01:28:31');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (60, 'SYSTEM', 'USERS', '3', 'Budi Darma', 'BLOCK', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 01:32:44');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (61, 'SYSTEM', 'USERS', '3', 'Budi Darma', 'UNBLOCK', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 01:32:50');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (62, 'AUTH', NULL, '1', 'Super Administrator', 'LOGOUT', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 01:37:05');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (63, 'AUTH', NULL, '1', 'Super Administrator', 'LOGIN', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 01:38:34');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (64, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"REKONLINK\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kits\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\",\"maintenance_mode\":\"1\",\"maintenance_message\":\"Maaf lagi gangguan yah\"}', '{\"app_name\":\"REKONLINK\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kits\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\",\"maintenance_mode\":\"1\",\"maintenance_message\":\"Maaf lagi gangguan yah\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 01:41:36');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (65, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"REKONLINK\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kits\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\",\"maintenance_mode\":\"1\",\"maintenance_message\":\"Maaf lagi gangguan yah\"}', '{\"app_name\":\"REKONLINK\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kits\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\",\"maintenance_mode\":\"1\",\"maintenance_message\":\"Maaf lagi gangguan yah\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 01:42:54');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (66, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"REKONLINK\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kits\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\",\"maintenance_mode\":\"1\",\"maintenance_message\":\"Maaf lagi gangguan yah\"}', '{\"app_name\":\"REKONLINK\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kits\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\",\"maintenance_mode\":\"0\",\"maintenance_message\":\"Maaf lagi gangguan yah\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 01:43:04');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (67, 'AUTH', NULL, '3', 'Budi Darma', 'LOGOUT', NULL, NULL, 3, 'Budi Darma', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-05 01:43:18');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (68, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"REKONLINK\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kits\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\",\"maintenance_mode\":\"0\",\"maintenance_message\":\"Maaf lagi gangguan yah\"}', '{\"app_name\":\"REKONLINK\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kits\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\",\"maintenance_mode\":\"0\",\"maintenance_message\":\"Maaf lagi gangguan yah\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 01:46:56');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (69, 'AUTH', NULL, '3', 'Budi Darma', 'LOGIN_FAILED', NULL, '{\"reason\":\"Wrong password\",\"attempt\":1}', NULL, NULL, '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-05 01:47:42');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (70, 'AUTH', NULL, '3', 'Budi Darma', 'LOGIN_FAILED', NULL, '{\"reason\":\"Wrong password\",\"attempt\":2}', NULL, NULL, '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-05 01:47:43');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (71, 'AUTH', NULL, '3', 'Budi Darma', 'LOGIN', NULL, NULL, 3, 'Budi Darma', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-05 01:47:49');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (72, 'SYSTEM', 'ROLES', '2', 'Admin', 'UPDATE', '{\"id\":\"2\",\"role_name\":\"Admin\",\"description\":\"Akses administrasi terbatas\",\"is_superadmin\":\"0\",\"created_at\":\"2026-03-04 23:10:23\",\"updated_at\":null,\"deleted_at\":null}', '{\"role_name\":\"Admin\",\"description\":\"Akses administrasi terbatass\",\"updated_at\":\"2026-03-05 01:49:52\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 01:49:52');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (73, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"REKONLINK\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kits\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\",\"maintenance_mode\":\"0\",\"maintenance_message\":\"Maaf lagi gangguan yah\"}', '{\"app_name\":\"REKONLINKs\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kits\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\",\"maintenance_mode\":\"0\",\"maintenance_message\":\"Maaf lagi gangguan yah\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 02:00:38');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (74, 'SYSTEM', 'SETTINGS', NULL, NULL, 'UPDATE', '{\"app_name\":\"REKONLINKs\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"active_theme\":\"adminlte2\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kits\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\",\"maintenance_mode\":\"0\",\"maintenance_message\":\"Maaf lagi gangguan yah\"}', '{\"app_name\":\"REKONLINKs\",\"app_version\":\"1.0.0\",\"app_description\":\"Enterprise-grade CodeIgniter 3 Starter Kit\",\"footer_text\":\"\\u252c\\u00ae 2026 Starter Kits\",\"sidebar_layout\":\"topnav\",\"skin_color\":\"purple\",\"login_attempts\":\"3\",\"backup_path\":\".\\/uploads\\/backups\\/\",\"maintenance_mode\":\"0\",\"maintenance_message\":\"Maaf lagi gangguan yah\",\"app_logo\":\"logo_1772647309.png\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 02:01:49');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (75, 'AUTH', NULL, '3', 'Budi Darma', 'LOGOUT', NULL, NULL, 3, 'Budi Darma', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-05 02:02:01');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (76, 'AUTH', NULL, '3', 'Budi Darma', 'LOGIN', NULL, NULL, 3, 'Budi Darma', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-05 02:03:00');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (77, 'SYSTEM', 'ROLES', '2', 'Admin', 'UPDATE', '{\"id\":\"2\",\"role_name\":\"Admin\",\"description\":\"Akses administrasi terbatass\",\"is_superadmin\":\"0\",\"can_add_user\":\"0\",\"can_view_all_users\":\"0\",\"created_at\":\"2026-03-04 23:10:23\",\"updated_at\":\"2026-03-05 01:49:52\",\"deleted_at\":null}', '{\"role_name\":\"Admin\",\"description\":\"Akses administrasi terbatass\",\"can_add_user\":1,\"can_view_all_users\":1,\"updated_at\":\"2026-03-05 02:13:02\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 02:13:02');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (78, 'SYSTEM', 'ROLES', '2', 'Admin', 'UPDATE', '{\"id\":\"2\",\"role_name\":\"Admin\",\"description\":\"Akses administrasi terbatass\",\"is_superadmin\":\"0\",\"can_add_user\":\"1\",\"can_view_all_users\":\"1\",\"created_at\":\"2026-03-04 23:10:23\",\"updated_at\":\"2026-03-05 02:13:02\",\"deleted_at\":null}', '{\"role_name\":\"Admin\",\"description\":\"Akses administrasi terbatass\",\"can_add_user\":0,\"can_view_all_users\":1,\"updated_at\":\"2026-03-05 02:13:27\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 02:13:27');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (79, 'AUTH', NULL, '3', 'Budi Darma', 'LOGOUT', NULL, NULL, 3, 'Budi Darma', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-05 02:13:40');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (80, 'AUTH', NULL, '3', 'Budi Darma', 'LOGIN', NULL, NULL, 3, 'Budi Darma', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-05 02:13:46');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (81, 'SYSTEM', 'ROLES', '2', 'Admin', 'UPDATE', '{\"id\":\"2\",\"role_name\":\"Admin\",\"description\":\"Akses administrasi terbatass\",\"is_superadmin\":\"0\",\"can_add_user\":\"0\",\"can_view_all_users\":\"1\",\"created_at\":\"2026-03-04 23:10:23\",\"updated_at\":\"2026-03-05 02:13:27\",\"deleted_at\":null}', '{\"role_name\":\"Admin\",\"description\":\"Akses administrasi terbatass\",\"can_add_user\":0,\"can_view_all_users\":0,\"updated_at\":\"2026-03-05 02:14:03\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 02:14:03');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (82, 'AUTH', NULL, '3', 'Budi Darma', 'LOGOUT', NULL, NULL, 3, 'Budi Darma', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-05 02:14:12');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (83, 'AUTH', NULL, '3', 'Budi Darma', 'LOGIN', NULL, NULL, 3, 'Budi Darma', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-05 02:14:17');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (84, 'SYSTEM', 'RECYCLE_BIN', NULL, 'All deleted data', 'EMPTY_BIN', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 02:40:30');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (85, 'AUTH', NULL, '3', 'Budi Darma', 'LOGOUT', NULL, NULL, 3, 'Budi Darma', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', '2026-03-05 02:44:25');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (86, 'AUTH', NULL, '3', 'Budi Darma', 'LOGIN', NULL, NULL, 3, 'Budi Darma', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 11:39:19');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (87, 'AUTH', NULL, '3', 'Budi Darma', 'LOGOUT', NULL, NULL, 3, 'Budi Darma', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 11:39:34');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (88, 'AUTH', NULL, '1', 'Super Administrator', 'LOGIN', NULL, NULL, 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 11:39:40');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (89, 'SYSTEM', 'MENU', '2', 'System Administration', 'UPDATE', '{\"id\":\"2\",\"menu_name\":\"System Administration\",\"menu_icon\":\"fa-cogs\",\"menu_link\":\"#\",\"parent_id\":null,\"menu_order\":\"1\",\"menu_status\":\"1\",\"created_at\":\"2026-03-04 23:10:23\",\"updated_at\":\"2026-03-05 00:16:50\",\"deleted_at\":null}', '{\"menu_name\":\"System Administration\",\"menu_icon\":\"fa fa-cogs\",\"menu_link\":\"#\",\"menu_order\":null,\"menu_status\":\"1\",\"parent_id\":null,\"updated_at\":\"2026-03-05 12:04:53\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 12:04:53');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (90, 'SYSTEM', 'MENU', '9', 'System Monitoring', 'UPDATE', '{\"id\":\"9\",\"menu_name\":\"System Monitoring\",\"menu_icon\":\"fa-desktop\",\"menu_link\":\"#\",\"parent_id\":null,\"menu_order\":\"3\",\"menu_status\":\"1\",\"created_at\":\"2026-03-04 23:10:23\",\"updated_at\":\"2026-03-05 00:16:50\",\"deleted_at\":null}', '{\"menu_name\":\"System Monitoring\",\"menu_icon\":\"fa fa-desktop\",\"menu_link\":\"#\",\"menu_order\":null,\"menu_status\":\"1\",\"parent_id\":null,\"updated_at\":\"2026-03-05 12:05:03\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 12:05:03');
INSERT INTO `activity_logs` (`id`, `module`, `sub_module`, `item_id`, `item_name`, `action`, `data_before`, `data_after`, `user_id`, `user_name`, `ip_address`, `user_agent`, `created_at`) VALUES (91, 'SYSTEM', 'MENU', '2', 'System Administration', 'UPDATE', '{\"id\":\"2\",\"menu_name\":\"System Administration\",\"menu_icon\":\"fa fa-cogs\",\"menu_link\":\"#\",\"parent_id\":null,\"menu_order\":\"0\",\"menu_status\":\"1\",\"created_at\":\"2026-03-04 23:10:23\",\"updated_at\":\"2026-03-05 12:04:53\",\"deleted_at\":null}', '{\"menu_name\":\" System Administration\",\"menu_icon\":\"fa fa-cogs\",\"menu_link\":\"#\",\"menu_order\":null,\"menu_status\":\"1\",\"parent_id\":null,\"updated_at\":\"2026-03-05 12:05:44\"}', 1, 'Super Administrator', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0', '2026-03-05 12:05:44');


#
# TABLE STRUCTURE FOR: backup_history
#

DROP TABLE IF EXISTS `backup_history`;

CREATE TABLE `backup_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `filename` varchar(255) NOT NULL,
  `filesize` varchar(50) DEFAULT NULL,
  `backup_type` enum('manual','scheduled') DEFAULT 'manual',
  `created_by` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

INSERT INTO `backup_history` (`id`, `filename`, `filesize`, `backup_type`, `created_by`, `created_at`) VALUES (1, 'backup_2026-03-05_00-11-23.sql', '42.46 KB', 'manual', 1, '2026-03-05 00:11:23');
INSERT INTO `backup_history` (`id`, `filename`, `filesize`, `backup_type`, `created_by`, `created_at`) VALUES (2, 'backup_2026-03-05_01-28-31.sql', '54.84 KB', 'manual', 1, '2026-03-05 01:28:31');


#
# TABLE STRUCTURE FOR: menu
#

DROP TABLE IF EXISTS `menu`;

CREATE TABLE `menu` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `menu_name` varchar(100) NOT NULL,
  `menu_icon` varchar(100) DEFAULT 'fa fa-circle-o',
  `menu_link` varchar(255) DEFAULT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `menu_order` int(5) NOT NULL DEFAULT '0',
  `menu_status` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_parent` (`parent_id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4;

INSERT INTO `menu` (`id`, `menu_name`, `menu_icon`, `menu_link`, `parent_id`, `menu_order`, `menu_status`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, 'Dashboard', 'fa fa-dashboard', 'dashboard', NULL, 0, 1, '2026-03-04 23:10:23', '2026-03-05 00:16:50', NULL);
INSERT INTO `menu` (`id`, `menu_name`, `menu_icon`, `menu_link`, `parent_id`, `menu_order`, `menu_status`, `created_at`, `updated_at`, `deleted_at`) VALUES (2, ' System Administration', 'fa fa-cogs', '#', NULL, 0, 1, '2026-03-04 23:10:23', '2026-03-05 12:05:44', NULL);
INSERT INTO `menu` (`id`, `menu_name`, `menu_icon`, `menu_link`, `parent_id`, `menu_order`, `menu_status`, `created_at`, `updated_at`, `deleted_at`) VALUES (3, 'User Management', 'fa fa-users', 'admin/users', 2, 0, 1, '2026-03-04 23:10:23', '2026-03-05 00:16:50', NULL);
INSERT INTO `menu` (`id`, `menu_name`, `menu_icon`, `menu_link`, `parent_id`, `menu_order`, `menu_status`, `created_at`, `updated_at`, `deleted_at`) VALUES (4, 'Role Management', 'fa fa-shield', 'admin/roles', 2, 1, 1, '2026-03-04 23:10:23', '2026-03-05 00:16:50', NULL);
INSERT INTO `menu` (`id`, `menu_name`, `menu_icon`, `menu_link`, `parent_id`, `menu_order`, `menu_status`, `created_at`, `updated_at`, `deleted_at`) VALUES (5, 'Menu Management', 'fa fa-bars', 'admin/menus', 2, 2, 1, '2026-03-04 23:10:23', '2026-03-05 00:16:50', NULL);
INSERT INTO `menu` (`id`, `menu_name`, `menu_icon`, `menu_link`, `parent_id`, `menu_order`, `menu_status`, `created_at`, `updated_at`, `deleted_at`) VALUES (7, 'Settings', 'fa fa-wrench', 'admin/settings', 2, 0, 1, '2026-03-04 23:10:23', '2026-03-05 00:16:50', NULL);
INSERT INTO `menu` (`id`, `menu_name`, `menu_icon`, `menu_link`, `parent_id`, `menu_order`, `menu_status`, `created_at`, `updated_at`, `deleted_at`) VALUES (8, 'Database Backup', 'fa fa-database', 'admin/backups', 2, 1, 1, '2026-03-04 23:10:23', '2026-03-05 00:16:50', NULL);
INSERT INTO `menu` (`id`, `menu_name`, `menu_icon`, `menu_link`, `parent_id`, `menu_order`, `menu_status`, `created_at`, `updated_at`, `deleted_at`) VALUES (9, 'System Monitoring', 'fa fa-desktop', '#', NULL, 0, 1, '2026-03-04 23:10:23', '2026-03-05 12:05:03', NULL);
INSERT INTO `menu` (`id`, `menu_name`, `menu_icon`, `menu_link`, `parent_id`, `menu_order`, `menu_status`, `created_at`, `updated_at`, `deleted_at`) VALUES (10, 'Activity Log', 'fa fa-history', 'admin/activity_log', 9, 1, 1, '2026-03-04 23:10:23', '2026-03-05 00:16:50', NULL);
INSERT INTO `menu` (`id`, `menu_name`, `menu_icon`, `menu_link`, `parent_id`, `menu_order`, `menu_status`, `created_at`, `updated_at`, `deleted_at`) VALUES (11, 'Audit Trail', 'fa fa-file-text', 'admin/audit_trail', 9, 0, 1, '2026-03-04 23:10:23', '2026-03-05 00:16:50', NULL);
INSERT INTO `menu` (`id`, `menu_name`, `menu_icon`, `menu_link`, `parent_id`, `menu_order`, `menu_status`, `created_at`, `updated_at`, `deleted_at`) VALUES (14, 'Recycle Bin', 'fa fa-trash-o', 'admin/recycle_bin', 9, 3, 1, '2026-03-05 00:36:12', NULL, NULL);


#
# TABLE STRUCTURE FOR: migrations
#

DROP TABLE IF EXISTS `migrations`;

CREATE TABLE `migrations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) NOT NULL,
  `batch` int(11) NOT NULL,
  `executed_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

#
# TABLE STRUCTURE FOR: role_permissions
#

DROP TABLE IF EXISTS `role_permissions`;

CREATE TABLE `role_permissions` (
  `role_id` int(11) NOT NULL,
  `menu_id` int(11) NOT NULL,
  PRIMARY KEY (`role_id`,`menu_id`),
  KEY `menu_id` (`menu_id`),
  CONSTRAINT `role_permissions_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `role_permissions_ibfk_2` FOREIGN KEY (`menu_id`) REFERENCES `menu` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `role_permissions` (`role_id`, `menu_id`) VALUES (1, 1);
INSERT INTO `role_permissions` (`role_id`, `menu_id`) VALUES (1, 2);
INSERT INTO `role_permissions` (`role_id`, `menu_id`) VALUES (1, 3);
INSERT INTO `role_permissions` (`role_id`, `menu_id`) VALUES (1, 4);
INSERT INTO `role_permissions` (`role_id`, `menu_id`) VALUES (1, 5);
INSERT INTO `role_permissions` (`role_id`, `menu_id`) VALUES (1, 7);
INSERT INTO `role_permissions` (`role_id`, `menu_id`) VALUES (1, 8);
INSERT INTO `role_permissions` (`role_id`, `menu_id`) VALUES (1, 9);
INSERT INTO `role_permissions` (`role_id`, `menu_id`) VALUES (1, 10);
INSERT INTO `role_permissions` (`role_id`, `menu_id`) VALUES (1, 11);
INSERT INTO `role_permissions` (`role_id`, `menu_id`) VALUES (1, 14);
INSERT INTO `role_permissions` (`role_id`, `menu_id`) VALUES (2, 1);
INSERT INTO `role_permissions` (`role_id`, `menu_id`) VALUES (2, 2);
INSERT INTO `role_permissions` (`role_id`, `menu_id`) VALUES (2, 3);
INSERT INTO `role_permissions` (`role_id`, `menu_id`) VALUES (3, 1);


#
# TABLE STRUCTURE FOR: roles
#

DROP TABLE IF EXISTS `roles`;

CREATE TABLE `roles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `role_name` varchar(50) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `is_superadmin` tinyint(1) NOT NULL DEFAULT '0',
  `can_add_user` tinyint(1) NOT NULL DEFAULT '0',
  `can_view_all_users` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_role_name` (`role_name`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

INSERT INTO `roles` (`id`, `role_name`, `description`, `is_superadmin`, `can_add_user`, `can_view_all_users`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, 'Super Admin', 'Akses penuh ke seluruh sistem', 1, 0, 0, '2026-03-04 23:10:23', NULL, NULL);
INSERT INTO `roles` (`id`, `role_name`, `description`, `is_superadmin`, `can_add_user`, `can_view_all_users`, `created_at`, `updated_at`, `deleted_at`) VALUES (2, 'Admin', 'Akses administrasi terbatass', 0, 0, 0, '2026-03-04 23:10:23', '2026-03-05 02:14:03', NULL);
INSERT INTO `roles` (`id`, `role_name`, `description`, `is_superadmin`, `can_add_user`, `can_view_all_users`, `created_at`, `updated_at`, `deleted_at`) VALUES (3, 'User', 'Akses user biasa', 0, 0, 0, '2026-03-04 23:10:23', NULL, NULL);


#
# TABLE STRUCTURE FOR: settings
#

DROP TABLE IF EXISTS `settings`;

CREATE TABLE `settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text,
  `setting_group` varchar(50) DEFAULT 'general',
  `description` varchar(255) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_setting_key` (`setting_key`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4;

INSERT INTO `settings` (`id`, `setting_key`, `setting_value`, `setting_group`, `description`, `updated_at`) VALUES (1, 'app_name', 'REKONLINKs', 'general', 'Nama aplikasi', '2026-03-05 02:01:49');
INSERT INTO `settings` (`id`, `setting_key`, `setting_value`, `setting_group`, `description`, `updated_at`) VALUES (2, 'app_version', '1.0.0', 'general', 'Versi aplikasi', '2026-03-05 02:01:49');
INSERT INTO `settings` (`id`, `setting_key`, `setting_value`, `setting_group`, `description`, `updated_at`) VALUES (3, 'app_description', 'Enterprise-grade CodeIgniter 3 Starter Kit', 'general', 'Deskripsi aplikasi', '2026-03-05 02:01:49');
INSERT INTO `settings` (`id`, `setting_key`, `setting_value`, `setting_group`, `description`, `updated_at`) VALUES (4, 'active_theme', 'adminlte2', 'appearance', 'Tema aktif (adminlte2 / adminlte3)', '2026-03-04 23:45:34');
INSERT INTO `settings` (`id`, `setting_key`, `setting_value`, `setting_group`, `description`, `updated_at`) VALUES (5, 'sidebar_layout', 'topnav', 'appearance', 'Layout (sidebar / topnav)', '2026-03-05 02:01:49');
INSERT INTO `settings` (`id`, `setting_key`, `setting_value`, `setting_group`, `description`, `updated_at`) VALUES (6, 'skin_color', 'purple', 'appearance', 'Warna skin tema', '2026-03-05 02:01:49');
INSERT INTO `settings` (`id`, `setting_key`, `setting_value`, `setting_group`, `description`, `updated_at`) VALUES (7, 'footer_text', '┬® 2026 Starter Kits', 'appearance', 'Teks footer', '2026-03-05 02:01:49');
INSERT INTO `settings` (`id`, `setting_key`, `setting_value`, `setting_group`, `description`, `updated_at`) VALUES (8, 'login_attempts', '3', 'security', 'Maksimal percobaan login sebelum blokir', '2026-03-05 02:01:49');
INSERT INTO `settings` (`id`, `setting_key`, `setting_value`, `setting_group`, `description`, `updated_at`) VALUES (9, 'backup_path', './uploads/backups/', 'system', 'Path penyimpanan backup', '2026-03-05 02:01:49');
INSERT INTO `settings` (`id`, `setting_key`, `setting_value`, `setting_group`, `description`, `updated_at`) VALUES (10, 'maintenance_mode', '0', 'general', NULL, '2026-03-05 02:01:49');
INSERT INTO `settings` (`id`, `setting_key`, `setting_value`, `setting_group`, `description`, `updated_at`) VALUES (11, 'maintenance_message', 'Maaf lagi gangguan yah', 'general', NULL, '2026-03-05 02:01:49');
INSERT INTO `settings` (`id`, `setting_key`, `setting_value`, `setting_group`, `description`, `updated_at`) VALUES (12, 'app_logo', 'logo_1772647309.png', 'general', NULL, '2026-03-05 02:01:49');


#
# TABLE STRUCTURE FOR: users
#

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `nama` varchar(100) NOT NULL,
  `email` varchar(100) DEFAULT NULL,
  `no_telp` varchar(20) DEFAULT NULL,
  `avatar` varchar(255) DEFAULT 'default.png',
  `role_id` int(11) NOT NULL DEFAULT '1',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `is_blocked` tinyint(1) NOT NULL DEFAULT '0',
  `failed_login` int(3) NOT NULL DEFAULT '0',
  `last_login` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

INSERT INTO `users` (`id`, `username`, `password`, `nama`, `email`, `no_telp`, `avatar`, `role_id`, `is_active`, `is_blocked`, `failed_login`, `last_login`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, 'admin', '0192023a7bbd73250516f069df18b500', 'Super Administrator', 'admin@starterkit.local', '081254593695', 'default.png', 1, 1, 0, 0, '2026-03-05 11:39:40', '2026-03-04 23:10:23', '2026-03-05 01:21:38', NULL);
INSERT INTO `users` (`id`, `username`, `password`, `nama`, `email`, `no_telp`, `avatar`, `role_id`, `is_active`, `is_blocked`, `failed_login`, `last_login`, `created_at`, `updated_at`, `deleted_at`) VALUES (3, 'darma9989', '0192023a7bbd73250516f069df18b500', 'Budi Darma', 'darma09091989@gmail.com', '081254593695', 'default.png', 2, 1, 0, 0, '2026-03-05 11:39:19', '2026-03-05 01:26:58', '2026-03-05 01:32:50', NULL);


